# Generated by Django 4.2.4 on 2023-10-23 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, max_length=100, verbose_name='Статус')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(default='thematics/default.png', upload_to='thematics', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('room', models.CharField(max_length=100, verbose_name='Помещение')),
                ('date', models.TimeField(default=datetime.datetime(2023, 10, 23, 8, 58, 4, 278692, tzinfo=datetime.timezone.utc), verbose_name='Время')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 23, 8, 58, 4, 278692, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 10, 23, 8, 58, 4, 278692, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 10, 23, 8, 58, 4, 278692, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('thematics', models.ManyToManyField(null=True, to='exhibitions.thematic', verbose_name='Выставки')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
    ]
