# Generated by Django 4.2.5 on 2023-12-16 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_alter_exhibition_date_alter_exhibition_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.TimeField(default=datetime.datetime(2023, 12, 16, 11, 55, 35, 561442, tzinfo=datetime.timezone.utc), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 11, 55, 35, 561442, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 11, 55, 35, 561442, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 11, 55, 35, 561442, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
